/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the web application is ready to start
//
function load()
{
    dashcode.setupParts();
}


function fieldButtonClick(event)
{
    window.open("http://127.0.0.1:8000/field/")
}


function marketButtonClick(event)
{
    window.open("http://127.0.0.1:8000/market/")
}


function accountButtonClick(event)
{
    window.open("http://127.0.0.1:8000/account/")
}
