/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the web application is ready to start
//
function load()
{
    dashcode.setupParts();
}


function buyButtonClick(event)
{
    // Insert Code Here
}


function sellButtonClick(event)
{
    // Insert Code Here
}


function wantedClick(event)
{
    // Insert Code Here
}


function backHomeButtonClick(event)
{
    window.open("http://127.0.0.1:8000/html/")
}
